const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT = "LOGOUT";

export { LOGIN_REQUEST, LOGIN_FAILURE, LOGIN_SUCCESS, LOGOUT };
